language: c

compiler:
  - gcc
  - clang

env:
  -
  - ARCHFLAGS='-m32'

install:
  - sudo apt-get update
  - sudo apt-get install -y gcc-multilib
  - sudo apt-get install -y zlib1g-dev
  - sudo apt-get install -y zlib1g-dev:i386
  - sudo apt-get install -y gcc

script:
  - make
