language: c
dist: trusty

compiler:
  - gcc
  - clang

env:
  -
  - CFLAGS='-m32'

install:
  - sudo apt-get update
  - sudo apt-get remove -y oracle-java9-installer
  - sudo apt-get install -y gcc-multilib
  - sudo apt-get install -y zlib1g-dev
  - sudo apt-get install -y zlib1g-dev:i386
  - sudo apt-get install -y gcc

  - wget http://mirrors.kernel.org/ubuntu/pool/universe/m/minizip/libminizip-dev_1.1-8_amd64.deb
  - wget http://mirrors.kernel.org/ubuntu/pool/universe/m/minizip/libminizip1_1.1-8_amd64.deb
  - sudo dpkg -i libminizip1_1.1-8_amd64.deb
  - sudo dpkg -i libminizip-dev_1.1-8_amd64.deb

script:
  - make

