language: c

compiler:
  - gcc

install:
  - sudo apt-get update
  - sudo apt-get install -y gcc-multilib
  - sudo apt-get install -y zlib1g-dev
  - sudo apt-get install -y zlib1g-dev:i386

script:
  - make
