language: c
dist: trusty

compiler:
  - gcc
  - clang

env:
  -
  - CFLAGS='-m32'

install:
  - sudo apt-get update
  - sudo apt-get install -y gcc-multilib
  - sudo apt-get install -y zlib1g-dev
  - sudo apt-cache search minizip
  - sudo apt-get install -y libminizip-dev
  - sudo apt-get install -y zlib1g-dev:i386
  - sudo apt-get install -y gcc

script:
  - make
